
name: Miran Oh | PhD in Linguistics @ USC
title: Miran Oh
email: miranoh@usc.edu
description: > # this means to ignore newlines until "baseurl:"
  I'm Miran Oh, a second year PhD student in Linguistics at University of Southern California
baseurl: "" # the subpath of your site, e.g. /blog

url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  miranoh

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
